apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: evil-pod
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: evil
    spec:
      # 
      # hostNetwork:true
      containers:
      - name: evil-pod
        image: nginx:latest
